name: Build Phar and Pack sfx

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-phar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: box

    - name: Run box compile
      run: box compile
      shell: /usr/bin/bash -e {0}
      env:
        COMPOSER_PROCESS_TIMEOUT: 0
        COMPOSER_NO_INTERACTION: 1
        COMPOSER_NO_AUDIT: 1

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: php-openbmclapi-phar
        path: ./build/php-openbmclapi.phar