name: Build Phar and Pack sfx

on:
  workflow_dispatch:

jobs:
  build-phar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup PHP with tools
    uses: shivammathur/setup-php@v2
    with:
      php-version: '8.3'
      tools: box

    - name: build-phar
      run: |
        box compile
