name: Build Phar and Pack sfx

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-phar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: box

    - name: Install composer
      run: composer install
      shell: /usr/bin/bash -e {0}
      env:
        COMPOSER_PROCESS_TIMEOUT: 0
        COMPOSER_NO_INTERACTION: 1
        COMPOSER_NO_AUDIT: 1

    - name: Run box compile
      run: box compile
      shell: /usr/bin/bash -e {0}
      env:
        COMPOSER_PROCESS_TIMEOUT: 0
        COMPOSER_NO_INTERACTION: 1
        COMPOSER_NO_AUDIT: 1

    - name: Upload Phar
      uses: actions/upload-artifact@v2
      with:
        name: php-openbmclapi-phar
        path: ./build/php-openbmclapi.phar

  pack-sfx:
    needs: build-phar
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      run: |
        git clone https://github.com/crazywhalecc/static-php-cli.git
        cd static-php-cli
        bin/setup-runtime

    - name: Setup static-php-cli
      run: |
        cd static-php-cli
        bin/php bin/composer update
        bin/php bin/spc doctor --auto-fix
        bin/php bin/spc download --with-php=8.1 --for-extensions "curl,openssl,phar,swoole,zlib,zstd"

    - name: Build micro
      run: |
        cd static-php-cli
        bin/php bin/spc build --build-micro --with-micro-fake-cli "curl,openssl,phar,swoole,zlib,zstd"

    - name: Download Phar Artifact
      uses: actions/download-artifact@v2
      with:
        name: php-openbmclapi-phar
        path: ./static-php-cli
        
    - name: Pack phar
      run: |
        cd static-php-cli
        bin/php bin/spc micro:combine php-openbmclapi.phar --output=php-openbmclapi-linux-x86_64

    - name: Upload sfx
      uses: actions/upload-artifact@v2
      with:
        name: php-openbmclapi-linux-x86_64
        path: |
          ./static-php-cli/php-openbmclapi-linux-x86_64
          ./static-php-cli/buildroot/license
