name: Build Phar and Pack sfx

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-phar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: box

    - name: Run box compile
      run: box compile
      shell: /usr/bin/bash -e {0}
      env:
        COMPOSER_PROCESS_TIMEOUT: 0
        COMPOSER_NO_INTERACTION: 1
        COMPOSER_NO_AUDIT: 1

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: php-openbmclapi-phar
        path: ./build/php-openbmclapi.phar

  pack-sfx:
    needs: build-phar
    runs-on: ubuntu-latest
    steps:
    - name: Download Phar Artifact
      uses: actions/download-artifact@v2
      with:
        name: php-openbmclapi-phar
        path: ./

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Setup static-php-cli
      run: |
        git clone https://github.com/crazywhalecc/static-php-cli.git
        cd static-php-cli
        composer update
        ./bin/spc doctor --auto-fix
        bin/spc download --for-extensions=openssl,swoole,zip,pcntl,zstd,phar,curl
        bin/spc download --all --with-php=8.3

    - name: Build micro
      run: |
        bin/spc build phar,curl,swoole,zstd,pcntl --build-micro --with-micro-fake-cli
        bin/spc micro:combine php-openbmclapi.phar -O /build/php-openbmclapi-linux-x86_64

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: php-openbmclapi-linux-x86_64
        path: /build/php-openbmclapi-linux-x86_64